[target.thumbv7em-none-eabi]
#runner = "arm-none-eabi-gdb -q -x ../openocd.gdb"
runner = "probe-rs run --chip STM32L432KCUx"

rustflags = [
	"-C", "link-arg=-Tlink.x",
]

[build]
target = "thumbv7em-none-eabi"
